model_selection:
  models:
    - xgboost
    - random_forest
    - logistic_regression
    - svm

optuna:
  n_trials: 75
  direction: maximize

xgboost:
  n_estimators:
    type: int
    low: 100
    high: 500
  max_depth:
    type: int
    low: 3
    high: 10
  learning_rate:
    type: float
    low: 0.01
    high: 0.3
  subsample:
    type: float
    low: 0.6
    high: 1.0
  colsample_bytree:
    type: float
    low: 0.6
    high: 1.0

random_forest:
  n_estimators:
    type: int
    low: 100
    high: 300
  max_depth:
    type: int
    low: 5
    high: 20
  min_samples_split:
    type: int
    low: 2
    high: 10
  min_samples_leaf:
    type: int
    low: 1
    high: 5

logistic_regression:
  C:
    type: float
    low: 0.01
    high: 10.0
  max_iter:
    type: int
    low: 100
    high: 500

svm:
  C:
    type: float
    low: 0.1
    high: 10.0
  kernel:
    type: categorical
    choices: ["linear", "rbf"]